# Generated by Django 5.0.6 on 2024-06-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("date", models.DateField()),
                ("rate", models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                "unique_together": {("currency", "date")},
            },
        ),
    ]
