# Generated by Django 5.0.6 on 2024-06-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangerate",
            name="name",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
