# Generated by Django 5.0.6 on 2024-06-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rates", "0002_exchangerate_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exchangerate",
            old_name="date",
            new_name="exchange_date",
        ),
        migrations.AlterUniqueTogether(
            name="exchangerate",
            unique_together={("currency", "exchange_date")},
        ),
    ]
